config/routes.rb
Rails.application.routes.draw do
  get 'mytrips/index'
  get 'plans/create'
  get 'posts/index'
  get '/users', to: redirect("/users/sign_up")
  post 'post/edit'
  resources :posts
  resources :plans
  devise_for :users
  get 'home/index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan_detail.rb
class PlanDetail < ApplicationRecord
    belongs_to :post
    validates :start_date,
    presence: true  
    validates :close_date,
    presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one :plan_detail
  accepts_nested_attributes_for :plan_detail
  belongs_to :user

  validates :trip_title,
    length: { maximum: 15},
    presence: true  
  validates :content,
    length: {maximum: 150},
    presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
      
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller? 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]


  def index
    @post = Post.all.order(created_at: "DESC")
    @detail = PlanDetail.all
  end
end

app/controllers/mytrips_controller.rb
class MytripsController < ApplicationController
  def index
    @post = Post.where(user_id: current_user.id).order(created_at: "DESC")
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def create
    @plan = PlanDetail.new(plan_params)
    @plan.save!
    calc_data(@plan)
    redirect_to edit_post_path(@plan.post_id)
  end

  def show
    @detail = PlanDetail.find(params[:id])
  end

  def update
    @detail = PlanDetail.find(params[:id])
    @detail.update_attributes(plan_params)
    calc_data(@detail)
    redirect_to edit_post_path(@detail.post_id)
  end

  def destroy
    @plan = PlanDetail.find(params[:id])
    @plan.destroy!
    calc_data(@plan)
    redirect_to edit_post_path(@plan.post_id)
  end

  def calc_data(data)
    plan = PlanDetail.where(post_id: data.post_id)
    cost = plan.sum(:cost)
    post = Post.find(data.post_id)
    post.total_cost = cost
    post.save!
    post.start_date = plan.minimum(:start_date)
    post.close_date = plan.maximum(:close_date)
    post.save! unless post.start_date.nil? || post.close_date.nil?
  end

  private

  def plan_params
    params.require(:plan_detail).permit(:plan_title, :user_id, :post_id, :content, :plan_title, :start_point, :goal_point, :duration, :start_date, :close_date, :cost)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end
  # def new
  #   @post = Post.new
  # end

  def create
    @post = Post.new(post_params)
    @post.save!
    respond_to do |format|
      format.html 
      format.js { render :test_create }
    end

  end

  def edit
    @post = Post.find(params[:id])
    @detail = PlanDetail.where(post_id: params[:id]) 
    @plan = PlanDetail.new
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    redirect_to edit_post_path(@post)
  end


  private

  def post_params
    params.require(:post).permit!
  end 

  def plan_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def calc_date(detail)
    start_date = detail.minimum(:start_date)
    close_date = detail.maximum(:close_date)
    if start_date.present? && close_date.present?
      start_trip = DateTime.parse(start_date.beginning_of_day.strftime("%Y-%m-%d"))
      end_trip = DateTime.parse(close_date.end_of_day.strftime("%Y-%m-%d")) 
      (end_trip - start_trip).numerator
    else
      0
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mytrips_helper.rb
module MytripsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div class="home_content">
  <div class="row">
    <div class="col-lg-6 mx-auto time_line">
      <% @post.find_each do |post| %>
        <% unless @detail.where(post_id: post.id).blank? %>
          <div class="card" id="home_card">
            <div class="flow_user_name"><%= post.user.name %></div>
            <%= image_tag("header.jpg", :class => "sample_photo") %>
            <div class="flow_trip_title">
              <%= post.trip_title %>
              <span class="float-right"><%= number_to_currency(post.total_cost ||= 0) %></span>
              <% if @detail.where(post_id: post.id).select("start_date").present? && @detail.where(post_id: post.id).select("close_date").present? %>
              <span class="float-right home_conunt_days">
                <%= calc_date(@detail.where(post_id: post.id)) %>泊<%= calc_date(@detail.where(post_id: post.id)) + 1 %>日&nbsp;&nbsp;
              </span>
              <% end %>
            </div>
            <%= link_to '', edit_post_path(post), id: 'card_detail_link' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.js.erb
$("#timeline_content").append("<div class='page'><%= escape_javascript(render(@posts)) %></div>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share trip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
</head>

<body>
</body>
</html>

  </head>

  <body>
    <header id="header" class="header">
      <%= link_to('Share Trip', root_path, id: 'home_title') %>
        <div class="header-btn">
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, class: 'btn-sm btn-light float-right devise-header-btn',id: 'logout_btn', :method => :delete) %>
            <%= link_to "+ New Plan", posts_index_path, class: 'btn btn-primary btn-sm float-right add-btn devise-header-btn' %>
            <%= link_to "Mytrip", mytrips_index_path, class: 'btn btn-primary btn-sm float-right add-btn devise-header-btn' %>
          <% else %>
            <%- if controller_name == 'home' %>
              <%= link_to "ログイン", new_user_session_path, class: 'btn-sm btn-light float-right devise-header-btn' %>
              <%= link_to "アカウント作成", new_user_registration_path, class: 'btn-sm btn-light float-right devise-header-btn' %>
            <% end %>
          <% end %>
        </div>
    </header>
  <div class="container-fluid body-content">
    <%= yield %>
  </div>
  </body>
</html>

app/views/mytrips/index.html.erb
<div class="home_content">
  <div class="row">
    <div class="col-lg-6 mx-auto time_line">
      <% @post.find_each do |post| %>
        <div class="card" id="home_card">
          <div class="flow_user_name"><%= User.find(post.user_id).name %></div>
          <%= image_tag("header.jpg", :class => "sample_photo") %>
          <div class="flow_trip_title"> 
            <%= post.trip_title %>
          </div>
          <%= link_to '', edit_post_path(post), id: 'card_detail_link' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/plans/_index.html.erb
<% if @detail.size > 0 %>
  <% @detail.order("start_date asc").each do |detail| %>
    <div class="form-user card">
      <div class="card-body">
        <div class="card-title">
            <div>
            <% if current_user.id == @post.user_id %>
              <%= link_to(content_tag(:i, 'close', class: 'material-icons delete_img'), plan_path(id: detail.id), :method => :delete) %>
              <%= link_to(content_tag(:i, 'edit', class: 'material-icons edit_img'), plan_path(id: detail.id)) %>
            <% end %>
            </div>

            <!-- <div>開始日</div> -->
            <div class="test">
              <div class="show_date float-left">
                <% if detail.start_date.present? %>
                 <div class=""><%= detail.start_date.strftime('%Y/%m/%d') %></div>
                 <div class=""><%= detail.start_date.strftime('%H:%M') %></div>
                <% else %>
                <div class=""><%= detail.start_date %></div>
                <% end %>
              </div>

              <div class="show_date d-flex align-items-center float-left">
                <% if detail.start_date.present? %>         
                &nbsp;~&nbsp;
                <% end %>
              </div>
            </div>

              <div class="show_date float-left">
                <% if detail.close_date.present? %>
                  <div class=""><%= detail.close_date.strftime('%Y/%m/%d') %></div>
                <% else %>
                  <div class=""><%= detail.close_date %></div>
                <% end %>
                <% if detail.close_date.present? %>
                <div class=""><%= detail.close_date.strftime('%H:%M') %></div>
                <% end %>
             </div>

            <div class="float_clear_left post_show_title"><%= detail.plan_title %>
              <div class="post_show_total float-right">
                <%= number_to_currency(detail.cost ||= 0) %>
              </div>
            </div>


            <div class="post_show_content float-left"><%= detail.start_point %></div>
            <div class="float-left">&nbsp;-&nbsp;</div>
            <div class="post_show_content float-left"><%= detail.goal_point %></div>
            
            <% if false %>
              <div>所要時間</div>
              <% if detail.duration.present? %>
                <div><%= detail.duration.strftime('%H:%M:%S') %></div>
              <% else %>
                <div><%= detail.duration %></div>
              <% end %>
            <% end %>

            <div class="post_show_content float_clear_left"><%= simple_format(detail.content) %></div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/plans/show.html.erb
<div class="row">
  <div class="col-lg-6 mx-auto">
    <div class="form-user card">
      <div class="card-body">
        <div class="card-title">          
          <%= form_for @detail, :url => plan_path do |f| %>
            <div class="row">
              <div class="col-lg-6">
                <div><%= f.label :plan_title, "Plan Title" %></div>
                <div><%= f.text_field :plan_title, class: "form-control post-card" %></div>
              </div>

              <div class="col-lg-6">
                <div><%= f.label :cost, "金額" %></div>
                <div><%= f.text_field :cost, class: "form-control post-card" %></div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-6">
                <div><%= f.label :start_date, "開始日" %></div>
                <div><%= f.datetime_field :start_date, class: "form-control post-card" %></div>
              </div>
  
              <div class="col-lg-6">
                <div><%= f.label :close_date, "終了日" %></div>
                <div><%= f.datetime_field :close_date, class: "form-control post-card" %></div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-6">
                <div><%= f.label :start_point, "出発地" %></div>
                <div><%= f.text_field :start_point, class: "form-control post-card" %></div>
              </div>
    
              <div class="col-lg-6">
                <div><%= f.label :goal_point, "目的地" %></div>
                <div><%= f.text_field :goal_point, class: "form-control post-card" %></div>
              </div>
            </div>

            <% if false %>
              <div><%= f.label :duration, "所要時間"%></div>
              <div><%= f.time_field :duration, class: "form-control post-card" %></div>
             <% end %>
            <div><%= f.label :content, "Detail" %></div>
            <div class="detail_content"><%= f.text_area :content,:size=>"60x10", class: "form-control post-card" %></div>
            <div><%= f.submit "Update", class: "btn btn-primary float-right add-btn" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_edit.html.erb
<%= form_for @post do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="form-user">
  <%= f.label :trip_title, "旅行タイトル" %>
  <%= f.text_field :trip_title %>
  <%= f.label :trip_title, "説明" %>
  <%= f.text_field :content %>
</div>
<%= f.submit "送信" %>
<% end %>

<div class="col-lg-2 side_bar">
<%= link_to "タイムライン", home_index_path, class: 'btn-square' %>
</div>

app/views/posts/_new.html.erb
<%= form_for @post, :url => posts_path, remote: true do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
    <div class="form-user card">
      <div class="card-body">
        <div class="card-title">          
          <div><%= f.label :trip_title, "Trip Title", class: "form-group" %></div>
          <div><%= f.text_field :trip_title, class: "form-control post-card" %></div>
          <div><%= f.label :trip_title, "説明", class: "form-group" %></div>
          <div><%= f.text_field :content, class: "form-control post-card" %></div>
          <div><%= f.submit "New", class: "btn btn-primary add-btn float-right" %></div>
        </div>
      </div>
    </div>
<% end %>

app/views/posts/_new_plan.html.erb
<%= form_for @plan, :url => plans_path do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="form-user card">
        <div class="card-body">
          <div class="card-title">
          <div class="row">
            <div class="col-lg-6">
              <%= f.hidden_field :post_id, :value => @post.id %>
              <div><%= f.label :plan_title, "Plan Title" %></div>
              <div><%= f.text_field :plan_title, class: "form-control post-card" %></div>
            </div>

            <div class="col-lg-6">
              <div><%= f.label :cost, "金額" %></div>
              <div><%= f.text_field :cost, class: "form-control post-card" %></div>
            </div>
            </div>

            <div class="row">
              <div class="col-lg-6">
                <div><%= f.label :start_date, "開始日" %></div>
                <div><%= f.datetime_field :start_date, class: "form-control post-card" %></div>
              </div>

              <div class="col-lg-6">
                <div><%= f.label :close_date, "終了日" %></div>
                <div><%= f.datetime_field :close_date, class: "form-control post-card" %></div>
              </div>
            </div>

          <div class="row">
            <div class="col-lg-6">
              <div><%= f.label :start_point, "出発地" %></div>
              <div><%= f.text_field :start_point, class: "form-control post-card" %></div>
            </div>

            <div class="col-lg-6">
              <div><%= f.label :goal_point, "目的地" %></div>
              <div><%= f.text_field :goal_point, class: "form-control post-card" %></div>
            </div>
          </div>
  
<% if false %>
            <div><%= f.label :duration, "所要時間"%></div>
            <div><%= f.time_field :duration, class: "form-control post-card" %></div>
<% end %>
            <div><%= f.label :content, "Detail" %></div>
            <div class="detail_content"><%= f.text_area :content,:size=>"60x10", class: "form-control post-card" %></div>
  
            <div><%= f.submit "Add", class: "btn btn-primary float-right add-btn" %></div>
          </div>
        </div>
      </div>
  　<% end %>

app/views/posts/_post.html.erb
<div class="col-lg-6 mx-auto time_line">
  <% unless @detail.where(post_id: post.id).blank? %>
    <div class="card" id="home_card">
      <div class="flow_user_name"><%= User.find(post.user_id).name %></div>
      <%= image_tag("header.jpg", :class => "sample_photo") %>
      <div class="flow_trip_title">
        <%= post.trip_title %>
        <% if post.total_cost.present? %>
          <span class="float-right"><%= post.total_cost %>円</span>
        <% else %>
          <span class="float-right">0円</span>
        <% end %>
        <% if @detail.where(post_id: post.id).select("start_date").present? && @detail.where(post_id: post.id).select("close_date").present? %>
        <span class="float-right">
          <%= calc_date(@detail.where(post_id: post.id)) %>泊<%= calc_date(@detail.where(post_id: post.id)) + 1 %>日&nbsp;&nbsp;
        </span>
        <% end %>
      </div>
      <%= link_to '', edit_post_path(post), id: 'card_detail_link' %>
    </div>
  <% end %>
</div>

app/views/posts/_show.html.erb
<div class="row">
  <div class="col-lg-6 mx-auto">
    <%= form_for @post do |f| %>
     <%= f.hidden_field :user_id, :value => current_user.id %>
     <div class="form-user card">
       <div class="card-body">
         <div class="card-title">
          <div><span class="float-right">合計:&nbsp;&nbsp;<%= number_to_currency(@post.total_cost ||= 0) %></span></div>
          <div><%= f.label :trip_title, "Trip Title", class: "form-group" %></div>
           <div><%= f.text_field :trip_title, class: "form-control post-card" %></div>
           <div><%= f.label :trip_title, "Detail", class: "form-group" %></div>
           <div><%= f.text_field :content, class: "form-control post-card" %></div>
           <div><%= f.submit "UPDATE", class: "btn btn-primary float-right add-btn" %></div>
         </div>
       </div>
     </div>
    <% end %>
  </div>
</div>

app/views/posts/_show_trip.html.erb
<div class="form-user card" id="title_card">
  <div class="card-body">
    <div class="card-title">
      <% if current_user.id == @post.user_id %>
        <%= link_to(content_tag(:i, 'edit', class: 'material-icons edit_img title_edit_img'), post_path(id: @post.id)) %>
      <% end %>
      <div class="show_title_content">
        <span class="post_show_title">
          <%= @post.trip_title %>
        </span>
        <span class="float-right post_show_total">
          <%= number_to_currency(@post.total_cost ||= 0) %>
        </span>
        <span class="float-right post_show_total">
        <% if @detail.where(post_id: @post.id).select("start_date").present? && @detail.where(post_id: @post.id).select("close_date").present? %>
          <%= calc_date(@detail.where(post_id: @post.id)) %>泊<%= calc_date(@detail.where(post_id: @post.id)) + 1 %>日&nbsp;&nbsp;
        <% else %>
          0泊1日&nbsp;&nbsp;
        <% end %>
      </span>
      </div>
    </div>
    <div class="post_show_content"><%= @post.content %></div>
  </div>
</div>

app/views/posts/_update_trip.html.erb
<%= form_for @post do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="form-user card">
    <div class="card-body">
      <div class="card-title">
       <div><span class="float-right">合計:&nbsp;&nbsp;<%= number_to_currency(@post.total_cost ||= 0) %></span></div>
       <div><%= f.label :trip_title, "Trip Title", class: "form-group" %></div>
        <div><%= f.text_field :trip_title, class: "form-control post-card" %></div>
        <div><%= f.label :trip_title, "Detail", class: "form-group" %></div>
        <div><%= f.text_field :content, class: "form-control post-card" %></div>
        <div><%= f.submit "UPDATE", class: "btn btn-primary float-right add-btn" %></div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-lg-6 mx-auto">
    <% if current_user.id == @post.user_id %>
      <%= render 'posts/show_trip' %>
    <% end %>
    <% if current_user.id == @post.user_id %>
      <%= render 'posts/new_plan' %>
    <% end %>
    <%= render '/plans/index' %>
  </div>
</div>


<% if false %>
<div class="col-lg-2 pl-0">
  <%= link_to "タイムライン", home_index_path, class: 'btn btn-primary float-left' %>
</div>
<% end %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-lg-6 mx-auto">
  <div id="target">
    <%= form_for @post, remote: true, url: posts_path do |f| %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="form-user card">
        <div class="card-body">
          <div class="card-title">        
            <div><%= f.label :trip_title, "Trip Title", class: "form-group" %></div>
            <div><%= f.text_field :trip_title, class: "form-control post-card" %></div>
            <div><%= f.label :trip_title, "説明", class: "form-group" %></div>
            <div><%= f.text_field :content, class: "form-control post-card" %></div>
            <div><%= f.submit "NEW", class: "btn btn-primary float-right add-btn" %></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

<% if false %>
<div class="col-lg-2 pl-0">
  <%= link_to "タイムライン", home_index_path, class: 'btn btn-primary float-left add-btn' %>
</div>
<% end %>

app/views/posts/new.js.erb
$('#edit_post').html("<%= escape_javascript(render 'posts/edit') %>");

app/views/posts/show.html.erb
<div class="row">
  <div class="col-lg-6 mx-auto">
    <%= form_for @post do |f| %>
     <%= f.hidden_field :user_id, :value => current_user.id %>
     <div class="form-user card">
       <div class="card-body">
         <div class="card-title">
          <div><span class="float-right">合計:&nbsp;&nbsp;<%= number_to_currency(@post.total_cost ||= 0) %></span></div>
          <div><%= f.label :trip_title, "Trip Title", class: "form-group" %></div>
           <div><%= f.text_field :trip_title, class: "form-control post-card" %></div>
           <div><%= f.label :trip_title, "Detail", class: "form-group" %></div>
           <div><%= f.text_field :content, class: "form-control post-card" %></div>
           <div><%= f.submit "UPDATE", class: "btn btn-primary float-right add-btn" %></div>
         </div>
       </div>
     </div>
    <% end %>
  </div>
</div>

app/views/posts/test_create.js.erb
$("#target").html("<%= j(render partial: 'posts/show', locals: { post: @post }) %>");